name: Test GoHook Actions

on:
    push:
        branches:
            - test-ci

jobs:
    test-gohook-actions:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run GoHook Actions
              uses: reim-developer/GoHookActions@v0.1.6
              with:
                config:
                    test.toml

            - name: Test GoHook is already downloaded.
              shell: bash
              run: |
                  ls 